// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uxjcerxyebgnpsbfsldw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4amNlcnh5ZWJnbnBzYmZzbGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxNTM1ODUsImV4cCI6MjA5MzcyOTU4NX0._S6zIdHZXJTD0-3H8fUnKGENwBN5dZW_8hU7nyhD7Tc";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});