// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
const SUPABASE_URL = "https://hfgyayjwskwjzxdjvjxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmZ3lheWp3c2t3anp4ZGp2anh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxODI5MzUsImV4cCI6MjA5MTc1ODkzNX0.3rp90SBq7quasBFGAVZiGhNPQvU76goEKmwYcn9tvqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});